- data/registers/spi_v1.yaml
All i2s status registers removed.
Renamed block to SPI from SPI1 for v2 (missed last time).
> Add SPI v1.

- data/registers/rcc_l0.yaml
- transform-RCC.yaml
> Remove enums from enable registers

- data/chips/STM32WB30CE.yaml
- data/chips/STM32WB35CC.yaml
- data/chips/STM32WB35CE.yaml
- data/chips/STM32WB50CG.yaml
- data/chips/STM32WB55CC.yaml
- data/chips/STM32WB55CE.yaml
- data/chips/STM32WB55CG.yaml
- data/chips/STM32WB55RC.yaml
- data/chips/STM32WB55RE.yaml
- data/chips/STM32WB55RG.yaml
- data/chips/STM32WB55VC.yaml
- data/chips/STM32WB55VE.yaml
- data/chips/STM32WB55VG.yaml
- data/chips/STM32WB55VY.yaml
- data/chips/STM32WB5MMG.yaml
- data/registers/rcc_wb55.yaml
- data/registers/syscfg_wb55.yaml
- parse.py
This enables initial support for STM32WB55 in the metapac.
> Add RCC and SYSCFG for STM32WB55

- data/chips/STM32WB10CC.yaml
- data/chips/STM32WB15CC.yaml
- data/chips/STM32WB30CE.yaml
- data/chips/STM32WB35CC.yaml
- data/chips/STM32WB35CE.yaml
- data/chips/STM32WB50CG.yaml
- data/chips/STM32WB55CC.yaml
- data/chips/STM32WB55CE.yaml
- data/chips/STM32WB55CG.yaml
- data/chips/STM32WB55RC.yaml
- data/chips/STM32WB55RE.yaml
- data/chips/STM32WB55RG.yaml
- data/chips/STM32WB55VC.yaml
- data/chips/STM32WB55VE.yaml
- data/chips/STM32WB55VG.yaml
- data/chips/STM32WB55VY.yaml
- data/chips/STM32WL54CC.yaml
- data/chips/STM32WL54JC.yaml
- data/chips/STM32WL55CC.yaml
- data/chips/STM32WL55JC.yaml
- data/chips/STM32WL55UC.yaml
- data/registers/exti_wb55.yaml
- data/registers/ipcc_v1.yaml
- parse.py
Add EXTI  for STM32WB55, IPCC for STM32WB55 and similar.
> Add EXTI and IPCC for STM32WB55

- .gitignore
- README.md
- d
There are two minor improvements:
* Ignore IntelliJ project files
* Check for the existence of some required commands before starting any processing
* Add a note in the readme on which tools are required and how to install `svd`
> Minor improvements

- data/chips/STM32F410C8.yaml
- data/chips/STM32F410CB.yaml
- data/chips/STM32F410R8.yaml
- data/chips/STM32F410RB.yaml
- data/chips/STM32F410T8.yaml
- data/chips/STM32F410TB.yaml
- data/registers/rcc_f4.yaml
- data/registers/rcc_f410.yaml
- data/registers/rcc_l4.yaml
- parse.py
Required for https://github.com/embassy-rs/embassy/pull/331
> Remove invalid bits from F4, L4 RCC

- data/registers/rcc_f4.yaml
- data/registers/rcc_l0.yaml
- data/registers/rcc_l4.yaml
See individual commit messages for details
> Fix RCC enable bits

- data/chips/STM32WL54CC.yaml
- data/chips/STM32WL54JC.yaml
- data/chips/STM32WL55CC.yaml
- data/chips/STM32WL55JC.yaml
- data/chips/STM32WL55UC.yaml
- data/registers/exti_wl5x.yaml
- parse.py
> Stm32wl55 exti regs

- data/registers/adc_v1.yaml
- data/registers/adc_v2.yaml
- data/registers/adc_v4.yaml
#172 Fixes this with the other versions
> Fix SAMPLE_TIME Defs

- data/registers/flash_g4.yaml
- stm32-data-gen/src/chips.rs
Compared to existing G0 flash peripheral, and differences check out on first look, though did not go through the datasheet with a fine comb.
> adding STM32G4 flash peripheral

- README.md
Fix wrong perimap link on README
> Fix wrong perimap link on README

- data/registers/pwr_wl5.yaml
this should allow consolidation of the bdcr code
> pwr/wl5: remove some enums

- data/registers/sdmmc_v1.yaml
This field was missing previously.
> Add stbiterr field for sdmmc_v1

- data/registers/adc_v2.yaml
- stm32-data-gen/src/rcc.rs
> g4: fix rcc adc generation and cleanup enums

- data/registers/rcc_f0.yaml
- data/registers/rcc_f3.yaml
- data/registers/rcc_f3_v2.yaml
- data/registers/rcc_g0.yaml
- data/registers/rcc_h50.yaml
- data/registers/rcc_l0.yaml
- data/registers/rcc_l0_v2.yaml
- data/registers/rcc_l1.yaml
- data/registers/rcc_l4.yaml
- data/registers/rcc_l4plus.yaml
- stm32-data-gen/src/rcc.rs
> rcc: fixup clock names and expand checking

- data/registers/wwdg_v2.yaml
- stm32-data-gen/src/chips.rs
Adds register definitions for the window watchdog (wwdg) v2.
> register definitions for window watchdog v2

- Cargo.lock
- Cargo.toml
- stm32-data-macros/Cargo.toml
- stm32-data-macros/src/lib.rs
- stm32-metapac-gen/Cargo.toml
- stm32-metapac-gen/src/data.rs
- stm32-metapac-gen/src/lib.rs
the intention is to expand this to become an independent crate, eventually
> add "enum debug" helper macro

- stm32-data-gen/src/rcc.rs
- stm32-data-serde/src/lib.rs
- stm32-metapac-gen/res/src/metadata.rs
- stm32-metapac-gen/src/data.rs
> add stop mode rcc data

- data/registers/quadspi_v1.yaml
- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/header.rs
rework of #311
Co-Authored-By: @Tupelov <64274155+Tupelov@users.noreply.github.com>
> Fix qspi for all chips.

- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/interrupts.rs
- stm32-data-gen/src/memory.rs
- stm32-data-gen/src/rcc.rs
- stm32-data-macros/src/lib.rs
- stm32-metapac-gen/src/data.rs
not some serious change, just followed `cargo clippy`'s advices.
But still need some careful check.
> refactor with clippy

- data/registers/syscfg_f3.yaml
- transforms/SYSCFG_F3.yaml
remove enum FPU_IE[0-5], PAGE[0-15]_WP and VBAT_MON
> syscfg-cleanup

- rust-toolchain.toml
- stm32-data-gen/src/gpio_af.rs
- stm32-data-gen/src/header.rs
- stm32-data-gen/src/interrupts.rs
- gen/interrupts: add a bit more logging
- gen/header: less strict irq parsing, it was missing some irqs.
> fix irq parsing

- data/registers/eth_v1a.yaml
- data/registers/eth_v1b.yaml
- data/registers/eth_v1c.yaml
- data/registers/eth_v2.yaml
- transforms/ETH.yaml
please do a full check on this PR, especially about **data/registers/eth_v2.yaml**. Although modification is done by transform yaml, I'm still not sure whether these changes are proper.
> Eth cleanup

- .github/ci/build.sh
- data/registers/cordic_v1.yaml
- stm32-data-gen/src/chips.rs
This MR adds support for the cordic_v1 unit for the stm32u5.
This is the last MR I have for now.
> add cordic_v1 for stm32u5

- data/registers/comp_v3.yaml
- stm32-data-gen/src/chips.rs
COMP1 and COMP2 on stm32wl differs only on the WINMODE bit for COMP2. I opted to skip that bit.
> add comp_v3 and apply to stm32wle

- data/registers/syscfg_h7.yaml
> Add TCM_AXI_SHARED_CFG to SYSCFG_UR17 for STM32H7

- Cargo.lock
- data/registers/timer_v1.yaml
- data/registers/timer_v2.yaml
- stm32-data-gen/Cargo.toml
- stm32-metapac-gen/Cargo.toml
- stm32-metapac-gen/res/src/metadata.rs
- stm32-metapac-gen/src/data.rs
This is the update after
will need a
~- [ ] Reset to remove "test yaml" commit~
> Add support for discountinous field

- data/registers/rcc_f3v3.yaml
- stm32-data-gen/src/rcc.rs
To be merge with https://github.com/embassy-rs/embassy/pull/2625
> Modify TIM(2)SW Clock Selection to use the new PLL1_P_MUL_2 name

- data/registers/pka_v1a.yaml
- data/registers/pka_v1b.yaml
- data/registers/pka_v1c.yaml
- stm32-data-gen/src/chips.rs
> add `PKA RAM` access

- data/registers/rcc_h5.yaml
- data/registers/rcc_h50.yaml
- stm32-data-gen/src/rcc.rs
the clock selection bit is named ADCDACSEL, shared between all ADCs and DACs
> fix ADC, DAC clock muxes for H5, U5

- stm32-data-gen/src/chips.rs
this shouldn't change any output
> move "UID" to "GHOST_PERIS"

- d.ps1
it confuse me a little while. XD
> update powershell script

- data/registers/pwr_h50.yaml
minimize the difference between H50x and H5 for PWR
> align PWR H50x to H5

- stm32-data-gen/src/chips.rs
> Add lcd peripheral for U0

- stm32-data-gen/src/chips.rs
> Add `lcdtft1_v1` as LTDC v1

- data/registers/lptim_v2a.yaml
- data/registers/lptim_v2b.yaml
- stm32-data-gen/src/perimap.rs
- Interface matching of `lptim_v2a` and `lptim_v2b`
- Adding interrupts
- Updating inline documentation
> Update multiple LPTIM-related fields

- data/registers/adc_g4.yaml
DMACFG Bit in ADC_CFGR change from Bitposition 0 to 1
> Update adc_g4.yaml -> DMACFG Bit in ADC_CFGR change from Bitposition 0 to 1

- data/registers/adc_f3.yaml
- data/registers/adc_f3_v1_1.yaml
- data/registers/adc_f3_v2.yaml
- data/registers/adc_g4.yaml
- data/registers/adc_v2.yaml
- data/registers/adc_v3.yaml
- data/registers/adc_v4.yaml
* Combine the identical EXTEN and JEXTEN enums
* Consistently combine JSQ1/JSQ2/etc fields into a JSQ array
> ADC injected register cleanup

- data/registers/vrefbuf_v1.yaml
- data/registers/vrefbuf_v2a1.yaml
- data/registers/vrefbuf_v2a2.yaml
- data/registers/vrefbuf_v2b.yaml
- stm32-data-gen/src/chips.rs
Also fixes some wrong docstrings for reference voltages.
> Fix missing VREFBUF peripheral on many chips

- stm32-data-serde/src/lib.rs
probe-rs needs it, please include 🥺
> Include memory access attrs in generated data

- d.ps1
- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/util.rs
> Add RegexSet

- stm32-data-gen/src/memory.rs
- stm32-data-serde/src/lib.rs
- stm32-metapac-gen/res/src/metadata.rs
- stm32-metapac-gen/src/data.rs
Based on reference manuals: rm0038,  rm0367, rm0376, rm0451, rm0377
> Added EEPROM support for L0/L1 series

- stm32-data-gen/src/generator.rs
This is the 2nd part for refactoring the chip handling after PR #604.
There are three separate commits to ease reviewing.
The refactoring is now complete and will hopefully make it easier to maintain and understand the module.
> Refactor and document DMA generation and create_peripherals_for_chip

- data/registers/adc_wba.yaml
- stm32-data-gen/src/perimap.rs
Adds support for the WBA series. 
I haven't yet tested this yet, so this will be put into draft mode.
> ADC Support for STM32WBA series

- data/registers/bdma_v1.yaml
> Fix double space

- data/registers/rcc_wb.yaml
cc https://github.com/embassy-rs/embassy/issues/4421
> rcc/wb: add rfwkupsel enum

- data/registers/adc_v3.yaml
Uses the descriptions given in https://cdn.sparkfun.com/assets/1/6/c/b/b/STM32WB55xx_Reference_Manual.pdf @ 16.7.5
> Improve registers for adc v3 CFGR2
