- data/registers/afio_f1.yaml
- data/registers/flash_f1.yaml
- parse.py
Added just the register needed for STM32 F1 support in Embassy. Not sure if `afio_f1` should be `afio_v1` (AFIO is needed for EXTI control for `gpio_v1`, so renaming probably makes sense).
> Add initial register mapping for STM32 F1 AFIO and FLASH

- data/registers/spi_v3.yaml
This leaves out some of the cfg attributes needed for SPI setup, alongside the ugly conditional includes.
> Unify SPI LSBFirst enums.

- data/registers/usart_v2.yaml
IXR was incorrect due to a few bits not being writable (or readable, even) in ICR
> USARTv2 split ixr into icr and isr

- data/chips/STM32L021D4.json
- data/chips/STM32L021F4.json
- data/chips/STM32L021G4.json
- data/chips/STM32L021K4.json
- data/chips/STM32L041C4.json
- data/chips/STM32L041C6.json
- data/chips/STM32L041E6.json
- data/chips/STM32L041F6.json
- data/chips/STM32L041G6.json
- data/chips/STM32L041K6.json
- data/chips/STM32L081CB.json
- data/chips/STM32L081CZ.json
- data/chips/STM32L081KZ.json
- stm32data/interrupts.py
Slight typo in the source files which caused the interrupts to not be matched correctly.
> Fix LPUART interrupts for the L0 family

- data/registers/otgfs_v1.yaml
- data/registers/otghs_v1.yaml
This removes as many differences between FS and HS versions as possible.
The `GCCFG` register has a lot of variations between chips, because it deals with vbus, charging, etc detections. I think it can be fixed when the need arises, so I just left it as is for now
> Unify and cleanup USB OTG registers

- data/registers/otg_v1.yaml
The XCVRDLY bit is a poorly-documented feature of the Synopsis ULPI link IP which helps work around timing constraints in some ULPI PHYs. [More information here](https://github.com/stm32-rs/synopsys-usb-otg/pull/17#issue-841324871).
> USB OTG: Add XCVRDLY bit

- README.md
Found out that `--bin` is required to run the generation commands. Got this error:
```shell
❯ cargo run --release stm32-data-gen
error: `cargo run` could not determine which binary to run. Use the `--bin` option to
specify a binary, or the `default-run` manifest key.
available binaries: stm32-data-gen, stm32-metapac-gen
```
> chore(docs): update readme generate section

- stm32-data-gen/src/chips.rs
Fixes I2C2 peripheral for the following chips:
- STM32F072C(8-B)Tx
- STM32F098CCUx
- STM32F098CCTx
- STM32F091C(B-C)Ux
- STM32F091C(B-C)Tx
- STM32F078VBTx
- STM32F078VBHx
- STM32F091V(B-C)Tx
- STM32F098VCTx
- STM32F078CBYx
- STM32F098VCHx
- STM32F091RCYx
- STM32F098RCYx
- STM32F072V(8-B)Hx
- STM32F098RCTx
- STM32F072RBHx
- STM32F078RBTx
- STM32F072R(8-B)Tx
- STM32F091R(B-C)Tx
- STM32F091RCHx
- STM32F071V(8-B)Hx
- STM32F078CBTx
- STM32F071CBYx
- STM32F072V(8-B)Tx
- STM32F098RCHx
- STM32F072RBIx
- STM32F091VCHx
- STM32F072CBYx
- STM32F078RBHx
- STM32F072C(8-B)Ux
- STM32F071V(8-B)Tx
- STM32F078CBUx
- STM32F071RBTx
- STM32F071C(8-B)Ux
- STM32F030RCTx
- STM32F070RBTx
- STM32F071C(8-B)Tx
- STM32F030CCTx
- STM32F070CBTx
> Added missing I2C IP version to `perimap`

- data/registers/flash_g4.yaml
- data/registers/rcc_g4.yaml
Modeled enums on STM32G0 definitions for RCC/FLASH peripherals of STM32G4. Checked enums against RM0440 Rev 7.
> add enums to STM32G4 Flash/RCC register YAMLs

- stm32-data-gen/src/chips.rs
+ SPI perimap for spi2s1_v2_4_Cube
> Update chips.rs to include perimap for SPI in STM32F410 MCUs

- .vscode/.gitignore
- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/interrupts.rs
This skips interrupts with a peripheral named can. This peripheral does not exist, but causes later duplicate interrupts with the correct peripheral to be skipped. If an IP file contains only interrupts with an incorrect CAN peripheral, this could cause those interrupts to be removed. However, I am not aware of such a file and am not sure how I would identify it.
> can: skip duplicate interrupt in f107

- README.md
In #199, @Dirbaio pointed me at the _fantastic_ index of generated docs for each chip variant supported by `stm32-metapac`. As a newcomer, it would have answered a lot of questions to find that link near the top of the README (which is where I went looking for it).
So, here's a PR. :-)
> README: add link to lovely generated docs site

- data/registers/syscfg_g0.yaml
It looks like the G0 file here picked up the F0-style "one remapping bit for both pins" field definition. The G0 series actually has C0-style dual remapping bits.
> G0 SYSCFG: fix PA11/PA12 RMP definitions

- data/registers/syscfg_c0.yaml
- data/registers/syscfg_g0.yaml
- Added docs from reference manual / fixed existing partial copy of reference manual docs
- Renamed System Flash case to SYSTEM_FLASH because FLASH was ambiguous (you really don't want to activate the System Flash when you wanted Main Flash, where your program lives!)
- Added Main Flash case.
Stylistically: note that main flash is actually `x0`. So the value I've given is valid for writes, but on read `== MAIN_FLASH` here could be misleading. Not sure how you prefer to handle cases like that.
> G0/C0: fix SYSCFG.CFGR1.MEM_MODE definition

- data/registers/gpio_v2.yaml
In an attempt to keep other people from making the mistake I described in #206, I've expanded the docs to explain how indexing of the fields works (because I don't expect users to read and understand the YAML).
These docs don't meet my normal standards for Rustdoc: they don't include a code example, they don't link the types involved using Markdown references, etc. However, it appears that the description field in the YAML is intended to be language-neutral; I don't think good API documentation can be language neutral, so you may want a way of adding language-specific documentation in the future.
For now, I have described it in very generic terms that apply to any language using 0-based array indexing, which does not cover all languages used in embedded (e.g. Lua, or in some cases Ada), …
> gpio_v2: expand docs on AFRx register pair to describe indexing.

- data/registers/gpio_v2.yaml
The field docs suggested that the index was in the range 0..15, which is not true in this case.
> gpio_v2: remove another case where indexing was potentially misleading

- d
New svd files sometimes fail with other errors like bad enum widths, so distinguish between that and a missing peripheral.
> extract-all: Distinguish missing and failure

- data/registers/hrtim_v1.yaml
- data/registers/hrtim_v2.yaml
- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/registers.rs
this pr *is* complete and aims to add the rest of the common registers and hrtim v2
v1.1 is binary compatible, but accessing the DLL is UB. However, that can be handled in the HAL.
closes #210
> hrtim: add common registers and v2

- data/registers/dac_v3.yaml
- stm32-data-gen/src/chips.rs
This PR should fix #222 by adding a DAC v3 variant based on v2.
TODO:
> WIP: fix #222 Add DAC v3 for STM32H7

- stm32-data-gen/src/chips.rs
ADC is currently unavailable for some STM32H7 chips like the H7A3. The registers seem to be the same across RM0455 and RM0399 and the ADC is working on a Nucleo H7A3ZI-Q board.
This PR therefore adds aditf5_v3_1 as a v4 ADC.
> Add aditf5_v3_1 ADC

- stm32-data-gen/src/chips.rs
The STM32U5 uses the same CRS peripheral as the L0, G0, and G4 products. This adds the association of the CRS v1 peripheral to the U5 CRS registers.
> Fix Issue #225. Add CRS v1 to STM32U5 chips.

- data/registers/adc_f3.yaml
the sample_time file depends on naming consistency
> adc/f3: fix sample time enum

- data/registers/adc_f3.yaml
Fix res enum  naming in adc_f3.yaml to match res enum naming in other chips
> fix adc_f3 resolution namings to match existing convention across

- data/registers/flash_h7.yaml
- data/registers/flash_h7ab.yaml
- stm32-data-gen/src/chips.rs
Some chips in the H7 family (stm32h7a3/b3/b0) have a different flash peripheral (different CR register and different latency/wait state configurations).
> split H7 flash for stm32h7a3/b3/b0 chips

- data/registers/quadspi_v1.yaml
Currently the FRCM (free-running clock mode) field is not supported in quadspi. However, on (some?) STM32H7 chips it is available.
On the other hand, they might not have a DMAEN field.
This PR adds the FRCM field and adds a hint that these fields are not available on all chips to the FRCM and DMAEN fields.
Their use should then be handled in the HAL, as discussed on the matrix chat.
> Add free-running clock mode for quadspi

- data/registers/rcc_wl5.yaml
- data/registers/rcc_wle.yaml
- stm32-data-gen/src/chips.rs
Use adc_g0 since very similar to the WLE one.
edit: added for STM32WL5x too (9c71725), since looks similar enough.
> Support STM32WLEx ADC peripheral

- data/registers/rcc_wl5.yaml
- data/registers/rcc_wle.yaml
This adds the MCOPRE & MCOSEL enums to the wl5 & wle targets. These both have an m4 core derived from the stm32l4, although with a slightly different set of clocks supporting the SubGHz radio. (The wl5 differs from the wle by also having an m0 core and some security support.)
> Add enums MCOPRE & MCOSEL to wl5 & wle targets

- Cargo.lock
- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/gpio_af.rs
- stm32-data-serde/Cargo.toml
- stm32-data-serde/src/lib.rs
This PR part of the "clean_pin" logic that removed all "_C" pins present on most H7 chips.
It also changes the `Pin` type to use a `String` to store the actual pin (e.g. PA5) to be able to accommodate the _C pins (e.g. PB2_C).
Since using strings breaks the sorting (alphabetic sorting != numeric sorting), a custom implementation of the `Ord` trait was necessary for the `Pin` struct.
> Handle "_C" pins

- data/extra/family/STM32F3.yaml
- stm32-data-gen/src/chips.rs
- stm32-data-serde/src/lib.rs
this will allow implementation of generated op-amp and comparator pins, where the selector is not specified in the xml files
> add man impl. pin signals

- .github/ci/build.sh
- data/extra/family/STM32G0.yaml
- data/extra/family/STM32G4.yaml
- data/extra/family/STM32WL.yaml
- data/registers/tamp_g0.yaml
- data/registers/tamp_g4.yaml
- data/registers/tamp_l5.yaml
- data/registers/tamp_u5.yaml
- data/registers/tamp_wl.yaml
- stm32-data-gen/src/chips.rs
Adds TAMP register block for the devices where I could understand how it was mapped. Some devices seems to have their TAMP/backup/RTC more intertwined and not as a separate register block. Those are not included.
Also not really sure why only u5 and l5 was mapped automatically while I had to add them manually for g0, g4 and wl through extra/families. I guess some field is missing in one of the sources?
Mainly adding this for gaining access to backup registers. Tested on stm32wle5cc.
> add TAMP register block for g0, g4, l5, u5 and wl

- data/registers/rcc_f0.yaml
- data/registers/rcc_f3.yaml
- data/registers/rcc_f3_v2.yaml
- data/registers/rcc_f7.yaml
- data/registers/rcc_h5.yaml
- data/registers/rcc_h50.yaml
- data/registers/rcc_h7.yaml
- data/registers/rcc_h7ab.yaml
- data/registers/rcc_h7rm0433.yaml
- data/registers/rcc_l0.yaml
- data/registers/rcc_l4.yaml
- data/registers/rcc_l5.yaml
- data/registers/rcc_u5.yaml
- data/registers/rcc_wb.yaml
- data/registers/rcc_wba.yaml
- data/registers/rcc_wl5.yaml
- data/registers/rcc_wle.yaml
- stm32-data-gen/src/chips.rs
Three changes:
1. The H7 parts from RM0433 have swapped bits for MediumLow and MediumHigh, and for this family they decided to just note it in the errata rather than change the reference manual. The F0, F3v2, F3, and F7 also have swapped bits according to their reference manuals. I created a separate rcc_h7rm0433.yaml just for this change.
2. Some of the reference manuals use slightly different names for the LSEDRV variants: Low, Lower, Lowest, LOW, etc. I unified these all to make it easier for the HAL.
3. The WB and WL families have LSEDRV registers but were missing the associated enums. Verified in the latest RMs.
> RCC: LSEDRV Register Fixes

- data/registers/tsc_v1.yaml
- data/registers/tsc_v2.yaml
- data/registers/tsc_v3.yaml
- stm32-data-gen/src/chips.rs
- transforms/TSC.yaml
Note: Some field sets have potential to be collapsed to two dimensional arrays, but `chiptool` doesn't support this.
> Add TSC (touch screen controller) peripheral

- data/registers/rcc_l5.yaml
enum/ADCSET was omitted on the STM32L5 processor family.
Change per discussion with dirbaio on Matrix channel
> Add enum/ADCSET to rcc_l5.yaml

- data/registers/can_bxcan.yaml
mostly just remove xxIE enum, also remove LBKM, and merge {R,T}IR_RTR into RTR, merge {R,T}IR_IDE into IDE
> bxcan-cleanup

- data/registers/rtc_v3l5.yaml
- data/registers/rtc_v3u5.yaml
- stm32-data-gen/src/chips.rs
I added the rtc registers for the stm32l5 series. As far as I understand there are no generated data in this repo anymore? At least not for this change I think. So there is no separate commit to put the generated data in as described in the README.
I also made some minor changes to the rtc_v3u5 registers. Mainly I used the array feature for all ALARM A and B registers. This was not used for all registers, but only for some.
> Add rtc registers for stm32l5

- stm32-data-gen/src/interrupts.rs
stm32-data-gen trace:
before:
```
TRACE stm32_data_gen::interrupts > parsing interrupts for chip STM32L051R8 core cm0p
...
TRACE stm32_data_gen::interrupts >   irq="TIM6_DAC_IRQn:Y,2V:TIM6,DAC:TIM6,DAC:"
TRACE stm32_data_gen::interrupts >     name=TIM6_DAC
TRACE stm32_data_gen::interrupts >     irq missing in C header, ignoring
...
```
after:
```
TRACE stm32_data_gen::interrupts > parsing interrupts for chip STM32L051R8 core cm0p
...
TRACE stm32_data_gen::interrupts >   irq="TIM6_DAC_IRQn:Y,2V:TIM6,DAC:TIM6,DAC:"
TRACE stm32_data_gen::interrupts >     name=TIM6_DAC
TRACE stm32_data_gen::interrupts >     peri_names: ["TIM6", "DAC"]
TRACE stm32_data_gen::interrupts >     part=TIM6
TRACE stm32_data_gen::interrupts >     part=TIM6, pp=["TIM6"]
TRACE stm32_data_gen::interrupts >     part=DAC …
```
> add irq name exception for "TIM6_DAC"

- data/registers/adf_v1.yaml
- stm32-data-gen/src/chips.rs
This MR adds the adf_v1.yaml to support the ADF unit on the STM32U5 series.
> Add support for ADF_v1 available on STM32U5

- data/registers/icache_v1.yaml
- stm32-data-gen/src/chips.rs
This MR adds icache_v1 for the STM32U5 series.
> Add icache_v1 for use with STM32U5

- data/registers/syscfg_f3.yaml
the collision happens inside RM0316, and among RM0364, RM0365 and RM0316.
> fix enum name collision, correct bit size and value

- stm32-data-gen/src/chips.rs
Update the PERIMAP to correctly associate the U535 and U545 chips with the appropriate version of the octospi implementation. These two sub-families use a different implementation than the rest of the U5 set of chips leading from the fact that only a single octospi peripheral is available on these chips, rather than two with the others.
> Update U5 Octospi mapping

- stm32-data-gen/src/header.rs
Octospi peripheral register address is getting set to the memory-mapped region for the U5 family. This alternate mapping for the peripheral corrects the register address that is generated.
> Fix register address mapping

- stm32-data-gen/src/chips.rs
perimap was missing for {UART, sci2_v1_1} target.
For instance, for STM32F103RC, taking the [STM32F103RC.json](https://github.com/embassy-rs/stm32-data-generated/blob/5f9a4a68c94a629409c5039c20ca1a7961347bed/data/chips/STM32F103RC.json#L2246);
Before:
```
{
"name": "UART4",
"address": 1073761280,
"rcc": {
[...]
```
After:
```
{
"name": "UART4",
"address": 1073761280,
"registers": {
"kind": "usart",
"version": "v1",
"block": "USART"
},
"rcc": {
[...]
```
> Fix UART definitions present in STM32F1 series

- data/registers/hash_v3.yaml
The lengths for CSR and HR register arrays are incorrect in the v3 hash implementation.
> Corrected hash v3 register arrays

- data/registers/adc_l0.yaml
- stm32-data-gen/src/chips.rs
The L0 ADC is mostly compatible to `v1` but with additional registers and it also has some rather smaller differences (like `SAMPLE_TIME`)
This is part one of the PR, part two for `embassy-rs` that uses the `l0`-peripherals will come a little later (but I tested it successfully already).
> adds adc support for L0

- data/registers/rcc_h7.yaml
Those were previously only called QUADSPI, which is needed on some chips like the STM32H745, but those bits are used as OCTOSPI1 bits on other chips like the STM32H723.
Should fix #384
> Add OCTOSPI1 register bits

- stm32-data-gen/src/header.rs
This fixes the address for the STM32H723 chips. It also updates a lot of other chips, hopefully those were incorrect before as well.
> Fix register address for OCTOSPI2 peripheral

- data/registers/syscfg_h7.yaml
Not sure if this is read-only or read-write, I couldn't find any info in the reference manual. I just marked it as read-only as that's what the other syscfg register was marked as.
Fixes #385
> Add SYSCFG_UR18 register

- data/registers/hash_v4.yaml
- stm32-data-gen/src/chips.rs
This change applies to the STM32U5 and STM32WBA series. Despite having the same ST IP version, these series have a minor change to the mapping of ALGO bits compared to v2. They also add the read-only field NBWP.
> Add HASH v4

- stm32-metapac-gen/src/lib.rs
combine with embassy-rs/chiptool#23, it removes *1k+* clippy warning and error from generated source code, with "stm32h573zi","pac","metadata" feature enabled.
> remove clippy warning and error from genrated files.

- data/registers/adc_h5.yaml
- data/registers/adccommon_h5.yaml
- transforms/ADC.yaml
- transforms/ADCCOMMON.yaml
do a format, add a few enums and fields, recreate transform yaml files.
by the way, I use a feature from embassy-rs/chiptool#26 to offset registers' byte_offsets of `ADC_COMMON` block.
Please consider merge that first before merge this PR, thanks!
> adc h5 improving

- data/registers/rcc_h7.yaml
The trait `rcc::RccPeripheral` is not implemented for CRYP on the H7 due to an apparent naming mismatch. This just changes the name for all registers `CRYPT` to `CRYP`.
> H7 RCC CRYP Register Naming

- data/registers/rcc_h7ab.yaml
- data/registers/rcc_h7rm0433.yaml
Missed these two files the other day. This should be all the locations where 'CRYP' is spelled 'CRYPT'.
> Correct 'CRYPT' to 'CRYP' in RCC

- Cargo.lock
- stm32-data-gen/Cargo.toml
- stm32-metapac-gen/Cargo.toml
- stm32-metapac-gen/src/data.rs
combine with embassy-rs/chiptool#27, this will make address of registers show as hex in output metapac, which align with RM, and make a little bit easier for us to comapre output with RM using eyes.
This doesn't touch stm32-data-gen, so there shouldn't be any changes in output json.
example of stm32-metapac changes:
stm32-metapac/src/chips/metadata_XXXX.rs
```diff
Peripheral {
name: "ADC1",
-    address: 1073816576,
+    address: 0x40012400,
registers: None,
```
stm32-metapac/src/chips/stm32XXXXXX/metadata.rs
```diff
MemoryRegion {
name: "BANK_1",
kind: MemoryRegionKind::Flash,
-    address: 134217728,
+    address: 0x8000000,
```
stm32-metapac/src/peripherals/XXX.rs
```diff
#[doc = "sample time register 1"]
#[inline(always)]
pub const fn smpr1(self) -> crate::common::Reg<regs::Smpr1, …
```
> make address of registers show as hex

- data/registers/cryp_v3.yaml
- stm32-data-gen/src/chips.rs
Adds a third CRYP register definition. cryp_v3 differs from cryp_v2 only in the NPBLB field of the CR register. For some unknown reason, none of the autogenerated register definitions seem to have this field. This change manually adds this field. Change is based on register definition from ST manual RM0399.
> Add cryp v3

- data/registers/rcc_l4plus.yaml
- data/registers/rcc_l5.yaml
Update octospi register labels for l4plus series and l5 series chips. Required for https://github.com/embassy-rs/embassy/pull/2672
> updated l4plus and l5 rcc registers

- data/registers/rcc_h7ab.yaml
H7ab does not have quadspi, but octospi. This fixes the generation of rcc blocks for the octospi1 peripheral
> Fix mislabeling for h7ab octospi rcc registers

- data/registers/adc_g4.yaml
- stm32-data-gen/src/chips.rs
Such as #440 and #448. ADC resolution enum is error.
I get the resolution bit from LL.
Here is the resolution bit in LL.
```c
#define LL_ADC_RESOLUTION_12B              (0x00000000UL)                      /*!< ADC resolution 12 bits */
#define LL_ADC_RESOLUTION_10B              (                 ADC_CFGR_RES_0)   /*!< ADC resolution 10 bits */
#define LL_ADC_RESOLUTION_8B               (ADC_CFGR_RES_1                 )   /*!< ADC resolution  8 bits */
#define LL_ADC_RESOLUTION_6B               (ADC_CFGR_RES_1 | ADC_CFGR_RES_0)   /*!< ADC resolution  6 bits */
```
So I copy from adc_v4 to adc_g4. And I change the ADC resolution enum.
> Fix ADC resolution enum for stm32g4

- data/registers/crc_v2.yaml
- data/registers/crc_v3.yaml
- data/registers/spi_v2.yaml
- data/registers/spi_v3.yaml
- data/registers/spi_v4.yaml
- data/registers/spi_v5.yaml
Most SPI peripherals are sensitive to the bit width of reads/writes to DR/TXDR/RXDR. This PR adds 8 and 16 bit wide versions of those registers to permit such accesses to be generated. This is the same approach already used for the [CRC DR](https://github.com/embassy-rs/stm32-data/blob/main/data/registers/crc_v2.yaml#L7) in crc_v2.yaml and crc_v3.yaml.
* spi_v1: This version is not sensitive to the bit width of the read or write. Only the low 8 bits are used.
* spi_v2: This version is sensitive to the bit width of the read or write. Data packing is automatically performed based on the width of the access. From the STM32G4 reference manual:
* spi_v3, spi_v4, spi_v5: These versions are sensitive to the bit width of the read or write. From the STM32U5 reference manual:
> Add 8 and 16 bit wide SPI data registers

- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/main.rs
- stm32-data-gen/src/memory.rs
- **Remove OTP from memory map.**
- **Sort memory regions  by addr.**
- **Manually maintain memory maps instead of parsing them from cubeprogdb.**
First step towards fixing #301
The cubeprogdb has turned out to be a quite bad data source. It's not granular
enough (it has one entry per chip die, not per chip) so the previous code joined
the data with the C headers and cubedb to fill in the gaps, essentialy "guessing"
stuff. This has been quite error prone (see #301) and hard to make fixes to.
Instead, we're going to manually maintain memory maps in a .rs file. This way, if
something is wrong we can simply go and fix it.
This commit just migrates the existing data, even if it's wrong. (it does fix
a few very minor mistakes). Next steps is actually fixing the memory maps.
> Manually maintain memory maps instead of parsing them from cubeprogdb.

- data/registers/flash_h50.yaml
The PRODUCT_STATE values are taken from the official HAL headers; I have only included enum variants which are definitively mentioned in RM0492, excluding other variants mentioned in the HAL headers for H50.
This PR also makes SWAP_BANK and BKSEL fields clearer.
> flash_h50: add PRODUCT_STATE enum; improve a couple other fields

- stm32-metapac-gen/res/src/lib.rs
- stm32-metapac-gen/src/lib.rs
As discussed in https://github.com/embassy-rs/embassy/pull/3005, let's export the list of all chip names and the list of all versions of all peripherals in the metadata, to be used in build.rs in embassy-stm32.
> Generate ALL_CHIPS and ALL_PERIPHERAL_VERSIONS metadata

- data/registers/timer_v1.yaml
- data/registers/timer_v2.yaml
- **Fix**: timer_v1 does not support field DBSS in register DCR
- Nitpick: in timer_v1, `block/TIM_2CH_CMP` does not need to override `DCR` and `DMAR`, because they are inherited from `block/TIM_1CH_CMP`
- Nitpick: in timer_v1, `fieldset/SMCR_ADV` was the same as `fieldset/SMCR_GP16`
- Nitpick: in timer_v1, `fieldset/DIER_ADV` does not need to override `BIE`, because it is inherited from `fieldset/DIER_1CH_CMP`
- **Fix**: in timer_v2, `block/TIM_2CH_CMP` should define `CCR_DITHER` as an array of len 2 (same as `CCR`)
- **Fix**: in timer_v2, `block/TIM_ADV` should define `ECR`
- Nitpick: in timer_v2, I put some registers in the same order as in timer_v1, to remove noise from the textual diff between timer_v1.yaml and timer_v2.yaml
I'm learning about the different types of STM32 timers and …
> Small timer fixes and rearrangements

- data/registers/timer_l0.yaml
- data/registers/timer_v1.yaml
- data/registers/timer_v2.yaml
- **Fix**: in timer_v1, I removed `DCR` from `block/TIM_GP16` by mistake in #484 :see_no_evil:
- **Fix**: timer_l0 does not support field `DBSS` in register `DCR`
- **Fix**: in timer_v1 and timer_v2, register `DIER` of `TIM_2CH_CMP` has field `TIE`
- Nitpick: in timer_l0, `fieldset/SMCR_2CH` is the same as `fieldset/GP_16`
> Further timer fixes

- stm32-data-gen/src/chips.rs
This PR allows the embassy-stm32 library to match on the LTDC peripheral missed by the existing `chips.rs` perimap. This was originally done to get embassy to expose an stm32h735g-dk LTDC peripheral but it also applies to many other stm32h7 mcus.
> Add LTDC support for STM32H7 mcus

- data/registers/sdadc_v1.yaml
- stm32-data-gen/src/chips.rs
- transforms/SDADC.yaml
This pull requests adds the register block for the Sigma-Delta ADC on the STM32F373 and STM32F301.
The documentation for the registers can be found in RM0313
I've never done a pull request to this repository, so I hope I've done everything correctly.
Before merging, there are a few open questions I have:
-  I want to remove the `{R,J}DATA{12,13}R` registers, because they only exist on the SDADC1 instance, and are not really necessary because they are just mirrors for the registers from other instances. Is there a way to do that via the transformations or can I do this manually?
- Unfortunaly, if I extract the YAML files using the `./d extract-all SDADC{1,2,3}` script, all three instances contain these registers. That's why I kept these registers in the first place
- Or maybe we should …
> Add registers for SDADC

- data/registers/vrefintcal_v1.yaml
The fieldset forces a 32bit word align during read. This causes a panic on devices where the vrefint value is stored at a 16bit word and not 32bit word boundry.
Fixes #504
> vrefint: Remove fieldset

- data/registers/rcc_g0.yaml
This is a fix for https://github.com/embassy-rs/embassy/issues/3223
This swaps the values of HSE and PLL1_Q variants so that they are correct.
Note that the register definition 5.4.22 in reference manual RM0444 is wrong but that this fix matches the c header files provided by ST for STM32Cube.
```c
// stm32g0xx_hal_rcc_ex.h#L437 
#if defined(RCC_CCIPR2_USBSEL)
/** @defgroup RCCEx_USB_Clock_Source USB Clock Source
* @{
*/
#if defined(RCC_HSI48_SUPPORT)
#define RCC_USBCLKSOURCE_HSI48         0x00000000U            /*!< HSI48 oscillator clock selected as USB clock */
#endif /* RCC_HSI48_SUPPORT */
#define RCC_USBCLKSOURCE_HSE           RCC_CCIPR2_USBSEL_0  /*!< HSE oscillator clock selected as USB clock */
#define RCC_USBCLKSOURCE_PLL           RCC_CCIPR2_USBSEL_1  /*!< PLL "Q" selected as …
```
> STM32G0: Fix USBSEL Variants for selecting HSE and PLL1_Q as USB Clock

- data/registers/mdios_v1.yaml
According to Stm32 RM 0399
MDIOS_DINRx should start at 0x100, after reserved section.
Discussed at https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$yITO9mef_jjcXBFsWWAA1xvRcVZsbPZ_5smrpVRYPMI?via=matrix.org
> Update offsets for mdio h7 and f7

- data/registers/spdifrx_h7.yaml
- stm32-data-gen/src/dma.rs
- stm32-data-gen/src/header.rs
- stm32-data-gen/src/normalize_peris.rs
- stm32-data-gen/src/perimap.rs
The STM32H7 SPDIFRX peripheral is slightly different from the existing one in the F4 and F7 series, so this adds support for the new version. The change is in the data register that can now have three different mappings, depending on a setting in the control register.
~~There is one problem that I don't know how to solve. This does not yet enable the `spdifrx` feature flag when building for (in my case) the `STM32H723VG` in embassy. I am trying to implement support for SPDIFRX there and this is the chip I will test it on.~~
I think that's not true, only my rust-analyzer tricking me. The verbose build does show `--cfg spdifrx` and `-cfg spdifrx_h7`.
> feat: Add STM32H7 SPDIFRX support

- data/registers/adc_u5.yaml
- stm32-data-gen/src/perimap.rs
Closes #502 
this code should work for adding adc4 support to the stm32u5xx family, I didn't get any answers on my issue, so I'm hoping what I have is ok. The only thing I'm somewhat unsure of is where I should've put the chips.rs entry.
> stm32u5xx adc4 support

- data/registers/otg_v1.yaml
- stm32-data-gen/src/rcc.rs
On some devices, such as the U5 and H7R/S series, the `GCCFG` register of the `OTG_HS` peripheral does not match the existing definitions (cp. [RM0477](https://www.st.com/resource/en/reference_manual/rm0477-stm32h7rx7sx-armbased-32bit-mcus-stmicroelectronics.pdf) sec. 62.14.18 and [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u575585-armbased-32bit-mcus-stmicroelectronics.pdf) sec. 73.14.18). They all have the USB core ID `5000`.
These changes are necessary to implement support for the peripheral on the H7R/S in https://github.com/embassy-rs/embassy/issues/3289. #519 may also be related, although there seem to be some additional changes necessary to get USB to work on those U5 parts.
> Add fieldset for GCCFG register variant on devices with USB core ID 5000

- stm32-data-gen/src/rcc.rs
This is needed for STM32U5 series USB_OTH_HS.
> Add OTGHS to USB_OTG_HS fallback clocks

- data/registers/otg_v1.yaml
This adds important, previously missing, registers for USBOTG core that were added in https://github.com/embassy-rs/embassy/pull/3348 to make USB Host work
> Add USBOTG registers from https://github.com/embassy-rs/embassy/pull/3348

- data/registers/ucpd_h5.yaml
- stm32-data-gen/src/perimap.rs
The STM32H5 UCPD registers deviate slightly from the current v1 driver. There is one additional field in `UCPD_CFGR2` and some others have to be removed.
> Fix: STM32H5-specific UCPD registers

- .github/ci/build.sh
- d
- data/registers/fmpi2c_v2.yaml
- data/registers/otg_v1.yaml
- stm32-data-gen/src/perimap.rs
Naming was inconsistent for FMPI2C, breaking the "doc" build.
> Fix FMPI2C block naming

- d.ps1
- stm32-data-gen/src/header.rs
Fix FMC base address and update `stm32-data-sources` revision in windows build script to match the linux one.
FMC base address was pointing to the wrong address (`0x6000_0000` instead of `0x4700_0400`). See related issue here - #462 .
Tested by building the project on Windows according to the README and utilizing the FMC with supported board (STM32H573).
> FMC Base Address Fix

- data/registers/pwr_u5.yaml
- data/registers/syscfg_u5.yaml
This adds some missing register definitions as noted in #519 to enable the USB OTG_HS PHY on some STM32U5 platforms.
> Add missing STM32U5 SYSCFG and PWR registers

- stm32-data-gen/src/perimap.rs
The aditf512_v3_0_H5 peripheral definition seems to be the same as the aditf5_v3_0_H5, just cleaned up.
Fixes #477
> Support STM32H23x and STM32H33x ADCs

- data/registers/timer_v1.yaml
Closes https://github.com/embassy-rs/stm32-data/issues/509
> fix(stm32h7): timer version assignements

- data/registers/hrtim_v1.yaml
- data/registers/hrtim_v2.yaml
This is consistent with the STM32 datasheet as well as all the other bitfields in the HRTIM_OUTxR register.
STM32H743 reference manual (HRTIMv2):
> Rename HRTIM FAULTX bits to FAULT

- data/registers/hrtim_v1.yaml
- data/registers/hrtim_v2.yaml
The following enums are removed from HRTIM register definitions, since they represent 1-bit values with unambiguous boolean interpretations:
* ACTIVEEFFECT (from Output Set register HRTIM_SETx?R)
* INACTIVEEFFECT (from Output Reset register HRTIM_RSTx?R)
* RESETEFFECT (from Reset register HRTIM_RSTxR)
* CAPTUREEFFECT (from Capture register HRTIM_CPT?xR)
* FLTEN (from Fault register HRTIM_FLTxR)
* OUTPUTSTATE and TIMAISR_DLYPRT (from Interrupt Status register HRTIM_TIMxISR)
* SYNCSTRT and SYNCRST (from Control register HRTIM_TIMxCR)
Happy to make changes if you disagree with the assessment of any of these as sufficiently boolean-like. Thanks!
We :heart: stm32-metapac
> Convert HRTIM boolean-like enums to bool

- data/registers/hrtim_v1.yaml
- data/registers/hrtim_v2.yaml
Sorry for the trickle of separate HRTIM PRs.... I keep thinking I'm done and then I find something else.
In this PR:
1. Combine SDTR and SDTF enums, since they're the same. (possible values are "positive" or "negative")
2. Combine TAU/TBU/TCU/TDU/TEU into a length-5 array.
> More HRTIM updates

- data/registers/ltdc_v1.yaml
See [stm32f75xxx and stm32f74xxx reference manual](https://www.st.com/resource/en/reference_manual/dm00124865-stm32f75xxx-and-stm32f74xxx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf) revision 8, section 18.7.21
I do not know with certainty that this change applies to all micros, because, to be quite frankly honest, I don't want to read 30 datasheets. However, I checked the one linked above and two others from different families (u5 and h7) and this change tracks in all of them.
> Fix BF1 enum

- Cargo.lock
- Cargo.toml
- stm32-data-gen/Cargo.toml
- stm32-metapac-gen/Cargo.toml
- stm32-metapac-gen/res/Cargo.toml
- stm32-metapac-gen/src/lib.rs
Update to the latest `chiptool` version, to add `Debug` and `defmt::Format` impls for fieldsets, value enums and interrupt enums :partying_face: 
Follow up for https://github.com/embassy-rs/chiptool/pull/44
> Update to chiptool for more Debug impls and defmt::Format impls.

- stm32-data-gen/src/rcc.rs
Despite the reference manual and header files referring to these fields in terms of DTS, the SVD files insist on using TMPSENS.
I opted to do the mapping at lookup time rather than renaming all of the fields.
> Map h7rs TMPSENS* RCC fields to the DTS peripheral

- data/registers/adc_v4.yaml
This change was erroneously introduced (by me) in c039709968dae10e83bb7903731c27c3b49c9ebf, and only on the adc_v4. Whoops!
> Correction to JEXTEN field name in JSQR

- data/registers/rtc_v3.yaml
- data/registers/rtc_v3l5.yaml
- data/registers/rtc_v3u5.yaml
I'm currently working on implementing RTC alarms in `embassy-stm32` and noticed the `ALRWF` bit in the `ICSR` was missing in `stm32-metapac` for v3. So this PR adds the definition to the the RTC v3 definitions.
> Add missing ALRWF bit to ICSR register in RTC v3 yamls

- data/registers/rtc_v3.yaml
All other variants name this flag ALRIE, but was named ALRAIE for v3. Probably a copy/paste error or missed rename.
> Fix naming of ALRIE flag in rtc_v3

- stm32-data-gen/src/memory.rs
This PR restores the OTP configuration removed in https://github.com/embassy-rs/stm32-data/pull/460.
I hope that I got the configuration right for all the series. The regions vary in size from 528 bytes (yes 16*32+16) to 512 bytes and 1k and 2k with many different locations. The data is based on the information in the header files and extracted with a `grep OTP *.h`.
Note that I had to make a new `mem` macro variant because of the odd sizes. Don't know if that is the best approach.
I have verified that it is correct for stm32f429 that I am on myself.
> Add OTP flash memory configuration

- data/registers/opamp_l4.yaml
- stm32-data-gen/src/perimap.rs
- transforms/OPAMP.yaml
I currently work on an L4 where I need the OpAmp and had to find out the definitions are missing. This is my attempt at extracting the register information following the documentation in the Readme. I extended the existing transformers from other Opamps and used the extracted `l4x1.yaml` as base. All the `l4xx.yaml` are identical, except a description error in the `l4x3.yaml`. The other l4-Variants (`l412`, `l4[pr]x`) appeared to be diffenent.
I do have some questions:
* Some larger variants have two opamps. The existing transformers delete those. The register map for both OpAmps is identical with a different offset. So I think this is fine, but not really sure how this is handled.
* I applied some manual changes to the yaml besides the transformers:
* For the descriptions I replaced with …
> Added STM32L4 OPAMP data

- data/registers/opamp_l4.yaml
rename OPAEN to OPAMPEN to match the name used by the other OPAMP variants
> opamp_l4: align enable register name

- data/registers/flash_g4c4.yaml
The bitsize for the number of flash pages (`PNB`) in the `FLASH_CR` is incorrect for category 4 devices (STM32G491, STM32G4A1).
As a result, erasing a page in bank 2 in single-bank mode will incorrectly erase the corresponding bank 1 page.
> Incorrect bit size for FLASH_CR PNB for g4c4

- data/registers/dma2d_v2.yaml
- stm32-data-gen/src/perimap.rs
Hi,
I have been busy building out the DMA2D driver for embassy-stm32 and I noticed some small issues relating to auto-generated config. The DMA2D peripheral is used for graphics applications and has the potential to vastly reduce render times on large displays. I used section 20 of rm0456 to double check everything. The changes are outlined as follows:
- Changed the documentation to make grammatical sense (cosmetic but nice).
- Fixed the `OCOLR` which was incorrectly represented due to an unusual setup in the reference manual (the register is duplicated to demonstrate all possible permutations of color modes). IMO. it is better to expose the raw register value (u32) and handle the permutations in code since as all bit values are valid but mean different things depending on setup in …
> Switch stm32u5 to dma2d-v2 and manually corrected yaml

- data/registers/adc_g0.yaml
- data/registers/adc_u0.yaml
- data/registers/adc_u5.yaml
Channel offsets were previously calculated incorrectly:
```rust   
#[doc = "Channel sampling time selection"]
#[inline(always)]
pub fn set_smpsel(&mut self, n: usize, val: bool) {
assert!(n < 19usize);
let offs = 8usize + n * 0usize;
self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
}
```
> Fix SMPSEL channel bit offset

- stm32-data-gen/src/gpio_af.rs
The test case is included in the embassy/embassy-stm32 trait.
> remove the MII and RMII prefixes from signal names

- data/registers/xspi_v1.yaml
- data/registers/xspim_v1.yaml
- stm32-data-gen/src/header.rs
- stm32-data-gen/src/perimap.rs
- transforms/XSPI.yaml
- transforms/XSPIM.yaml
I've tested this against a small example in embassy-stm32 [1]. Need to figure why single mode works but quad mode doesn't, but I think the PAC here is OK. 
@rickrogers-ionq 
[1] https://github.com/mkj/embassy/tree/dev/matt/xspi
> Add xspi_v1 and xspim_v1 from h7s svd

- stm32-data-gen/src/chips.rs
- stm32-data-gen/src/low_power.rs
- stm32-data-gen/src/main.rs
- stm32-data-gen/src/rcc.rs
- stm32-data-gen/src/registers.rs
- stm32-data-serde/src/lib.rs
Allows adding custom rules for the lowest possible stop mode for a peripheral.
This affects the embassy low-power executer, as the peripheral limits the available power modes when it's active.
Supporting information for the rules below:
I went to the `sources/headers` directory and ran `rg` for my MCU.
Checking the manual of the stm32wb55 shows the following:
So the header file is not accurate enough to differentiate between stop1 and stop2, but it's an indication at least.
According to the [manual](https://www.st.com/resource/en/reference_manual/rm0434-multiprotocol-wireless-32bit-mcu-armbased-cortexm4-with-fpu-bluetooth-lowenergy-and-802154-radio-solution-stmicroelectronics.pdf), the USART and the I2C should just work in lower power modes as well. At least as far as I understand.
> feat: add stop mode rules which override the fallback behavior

- data/registers/opamp_f3.yaml
- data/registers/opamp_g4.yaml
- data/registers/opamp_h_v1.yaml
- data/registers/opamp_h_v2.yaml
- data/registers/opamp_l4.yaml
- data/registers/opamp_u0.yaml
- Harmonized descriptions across OpAmp versions.
- Improved punctuation consistency: omit the period for fragments; include it for full sentences.
- Fixed various typos and copy/paste errors.
- Removed redundant phrases like “OPAMP” or “Operational amplifier” from register descriptions.
- Standardized enum and field names to reflect majority usage and improve cross-family consistency:
- USER_TRIM → USERTRIM
- OUTCAL → CALOUT (used in most families; RM0440 also uses CALOUT)
- Some changes diverge slightly from reference manual naming.
- Removed trivial enums and ensured descriptions are self-explanatory:
- OPAHSM, USERTRIM, OPAINTOEN, CALON, OPALPM, FORCE_VP, OUTCAL
- Identifier renames for clarity and consistency:
- U0: VM_SEL variant VINM → GPIO, NotConnected → NOT_CONNECTED
- L4: …
> Unify and clean up OpAmp descriptions and identifiers

- README.md
- d
- Introduce a new `gen-all` target in `d` to run JSON, PAC generation, and formatting in one step
- Slightly restructure README to ease getting started
- Add an overview of files and functionality
- Update Quick Guide in README to reference `./d gen-all`
- Remove outdated `parse.py` reference and point to `stm32-data-gen/src/perimap.rs` instead
> Add gen-all command to helper script and update README

- data/registers/adc_u5.yaml
- data/registers/adc_v4.yaml
This typo was inherited from the source SVDs. The typo is also present in the reference manual for the STM32H743 (!) but I think it's best to apply the correct name for consistency with all the other ADC versions that correctly name this field OSVR.
STM32H743 reference manual:
> Oversampling ratio register is OVSR, not OSVR

- data/extra/family/STM32H7.yaml
- stm32-data-gen/src/chips.rs
This commit does not introduce any PAC changes, the results are identical except that now all pins are sorted, also the ones read from data/extras. I wanted to do this in an extra commit to make reviewing easier, although it doesn't add value at the moment and is just a first step.
> Move pin cleanup from code to YAML, before adding more clean-up rules

- data/registers/rtc_v3h7rs.yaml
- stm32-data-gen/src/perimap.rs
I tried to generally match the `rtc_v3.yaml` format where possible.
The embassy rtc example for stm32h7rs now works after these updates.
> Add RTC support for h7rs

- stm32-data-gen/src/perimap.rs
This impacts the STM32C0 line, specifically:
* STM32C011F(4-6)Px
* STM32C031F(4-6)Px
* STM32C011F(4-6)Ux
* STM32C011D6Yx
* STM32C011J(4-6)Mx
* STM32C031K(4-6)Tx
* STM32C031C(4-6)Tx
* STM32C031C(4-6)Ux
* STM32C031G(4-6)Ux
* STM32C031K(4-6)Ux
Tested on STM32C0116F6
> Add support for RTC3 v4

- data/registers/rtc_v3c0.yaml
- stm32-data-gen/src/perimap.rs
The STM32C0 supports v3 of RTC. However it only supports a subset of the features.
Notably the differences are:
* No Wakeup unit / No Wakeup event
* Alarm is referenced as AlarmA
References:
* STM32 RTC v2/v3: AN4759 - Rev 10: https://www.st.com/resource/en/application_note/an4759-introduction-to-using-the-hardware-realtime-clock-rtc-and-the-tamper-management-unit-tamp-with-stm32-mcus-stmicroelectronics.pdf
* STM32C0: RM0490 - Rev 5: https://www.st.com/resource/en/reference_manual/rm0490-stm32c0x1-advanced-armbased-32bit-mcus-stmicroelectronics.pdf
Tested on STM32C011F6P6
> Add RTCv3 for the STM32C0

- stm32-data-gen/src/memory.rs
RegexMap is unfortunately sensitive to ordering, so the new WBA6 data was ignored. There are also some suspicious L1 entries but I'll not even try to untangle that.
> Fix WBA6x memory maps

- data/registers/flash_u5.yaml
- data/registers/flash_wba.yaml
- Part of a future addition for TrustZone support on WBA devices on Embassy
- Original work based off of WB devices, but more similar to U5
> Fixed missing fields for TrustZone on WBA series

- d
- data/registers/rcc_wba.yaml
- stm32-metapac-gen/res/Cargo.toml
In the process of trying to get the USB_OTG_HS working for a WBA6 device I found that the following fields were missing from the generated metapac.
I pulled the RCC registers off of the WBA*.svd files and performed the recommended transform. The transform needs a bit of work because it takes out stuff like "I2C2SEL" and turns it into "ICSEL". Anyways here's the most relevant changes.
> Added missing fields and enums for rcc_wba.yaml

- data/registers/rcc_h7rs.yaml
* stm32 h7rs series transitioned from OCTOSPI to XSPI
* this fix is required in order to select the xspi rcc mux channel
* eg, ```config.rcc.mux.xspi2sel = mux::Xspisel::PLL2_S;```
> change remaining OCTOSPI instances in rcc_h7rs.yaml to proper XSPI

- data/registers/sai_v4_2pdm.yaml
- stm32-data-gen/src/perimap.rs
Added SAI for WBA series of devices. There were some miscellaneous nonstandard unicode characters. I've replaced those. I've also added enums for non-trivial fields (number of mics, oversampling ratio)
> Added SAI for WBA on perimap.rs

- data/registers/hash_v3.yaml
- data/registers/hash_v4.yaml
Should be 4 bits not 2. This is required for sha384 and sha512.
> Correct hash v3 and v4 algo field

- data/registers/lptim_v2b.yaml
Added the UEDE ("Update event DMA request enable") single bit field to lptim_v2b.yaml, valid for all STM32U0 parts.
See reference manual RM0503 (rev. 4) section 27.7.5.
> stm32u0: Add UEDE field to LPTIMx_DIER register

- data/registers/rtc_v3l4.yaml
- stm32-data-gen/src/perimap.rs
The stm32l412 and stm32l422 use the v3 RTC register map. That map is slightly cut down as the alarms don't have binary mode selection and there is no underflow interrupt. This means we nee a slightly cut down version of the v3 register map for these parts. 
In Cube those parts are annotated having the rtc3_v2_0 version of the IP.
> stm32l4: Add cut down version of the v3 rtc map
